theme: jekyll-theme-dinky
title: Use TFOD models and datasets in a super easy way
description: A codebase for loading TFOD models and datasets in a super easy and pythonic way.
show_downloads: false
google_analytics: UA-239643393-2
